name: Docker test

on:
  pull_request:
    # Trigger on pull requests to master or develop
    branches:
      - main
      - develop
  push:
    # Trigger on pushes to master or develop and for git tag pushes
    branches:
      - main
      - develop


jobs:
  docker-example:
    runs-on: ubuntu-18.04
    steps:
      - name: foo
        run: |
            docker pull ghcr.io/testdockerorga/mala_conda_cpu:latest
            docker images
            #docker -D run -i -d --rm --name mala-cpu -v ${{ github.workspace }}:/home -w /home ghcr.io/testdockerorga/mala_conda_cpu
            for i in `seq 10`; do docker -D run -d -i --rm ghcr.io/testdockerorga/mala_conda_cpu  /bin/bash & done; wait
            echo "Exit code: $?"
            docker ps --all
